/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class newer_Sample_JNI */

#ifndef _Included_newer_Sample_JNI
#define _Included_newer_Sample_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     newer_Sample_JNI
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_newer_Sample_1JNI_intMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     newer_Sample_JNI
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_newer_Sample_1JNI_booleanMethod
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     newer_Sample_JNI
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_newer_Sample_1JNI_stringMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     newer_Sample_JNI
 * Method:    intArrayMethod
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_newer_Sample_1JNI_intArrayMethod
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
