#!/usr/bin/python
a=21
b=10
c=0
c=a+b
print (str(a)+"+"+str(b)+"="+str(c))
c=a-b
print (str(a)+"-"+str(b)+"="+str(c))
c=a*b
print (str(a)+"*"+str(b)+"="+str(c))
c=a/b
print (str(a)+"/"+str(b)+"="+str(c))
a=2
b=3
c=a**b
print (str(a)+"**"+str(b)+"="+str(c))
a=10
b=5
c=a//b
print (str(a)+"//"+str(b)+"="+str(c))
a=11.4
b=2.1
c=a//b
print (str(a)+"//"+str(b)+"="+str(c))
